### ISSUE TITLE
site has been down for 3 days

### ISSUE THREAD

**Issue by minuteworld** [nextchan/infinity-next#41]
for me anyway.

**Comment by minuteworld** [comment]
now 4

**Comment by minuteworld** [comment]
for a week.

**Comment by lluixhi** [comment]
@minuteworld 
We know. We need a new server because the previous host shut us down without warning or a chance to appeal the decision.

**Comment by minuteworld** [comment]
have an estimation till when the site comes back up?


tbh fam this might have been a good thing because it might've driven all the pedos away.
